name: Code Quality Check

on:
  push:
    branches:
      - master # Replace 'main' with your default branch if different
  pull_request:
    branches:
      - master # Replace 'main' with your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint and Prettier
        run: npx eslint . --ext js,jsx && npx prettier --check .
